from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class CourseStorage(Protocol):
    """Storage port used by course and calendar application services."""

    def safe_design_name(self, name: str) -> str: ...

    def saved_design_path(self, name: str) -> Path: ...

    def school_calendar_path(self, name: str) -> Path: ...

    def read_design(self) -> dict[str, Any]: ...

    def write_design(self, payload: dict[str, Any]) -> None: ...

    def list_saved_designs(self) -> list[dict[str, str]]: ...

    def read_saved_design(self, name: str) -> dict[str, Any]: ...

    def write_saved_design(self, name: str, payload: dict[str, Any]) -> dict[str, str]: ...

    def delete_saved_design(
        self,
        name: str,
        delete_calendars: bool = False,
        calendars: list[str] | None = None,
    ) -> dict[str, Any]: ...

    def list_school_calendars(self) -> list[dict[str, str]]: ...

    def read_school_calendar(self, name: str) -> dict[str, Any]: ...

    def write_school_calendar(self, name: str, payload: dict[str, Any]) -> dict[str, str]: ...


class AssignmentStorage(Protocol):
    """Storage port used by assignment dashboard application services."""

    def safe_teacher_report_path(self, name: str) -> Path: ...

    def list_assignment_reports(self) -> list[dict[str, Any]]: ...

    def read_assignment_report(self, name: str) -> dict[str, Any]: ...

    def list_activities(self) -> list[dict[str, Any]]: ...
